apiVersion: apps/V1
kind:   Deployment
metadata:
  name: tech-deploymnet
  lables:
     app: techapp
     
spec:
  replicas: 1
  selector:
    matchlabels:
      app: techapp

template:
  metadata:
    labels:
      app: techapp

spec:
  containers:
   - name: techapp
     image: govarthanank/httpd:V1
     imagePullPolicy: Always
    ports: 
      - containerPort: 8080

strategy:
  type: RollingUpdate
  rollingUpdate: 
    maxSurge: 1
    maxUnavailable: 1
