apiVersion: apps/v1
kind: Service
metadata:
  name: tech-service
  labels:
    app: techapp

spec:
  selector:
    matchLabels:
      app: techapp

  ports:
  - port: 8080
    targetPort: 8080

type: LoadBalancer
